import type { Metadata } from "next";
import { Providers } from "@/lib/redux/Provider";
import "../globals.css";
import { Navbar } from "@/components/Homepage/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <Navbar />
          <main className="container mx-auto px-14 py-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
